version: '3'
services:
  server:
    container_name: ssh-server
    hostname: server.mydomain.local
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      my-network:
        aliases:
          - server.mydomain.local
  pihole:
    container_name: pihole
    hostname: pihole.mydomain.local
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      my-network:
        aliases:
          - pihole.mydomain.local
  client:
    container_name: ssh-client
    hostname: laptop.mydomain.local
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      my-network:
        aliases:
          - laptop.mydomain.local

  ca:
    container_name: ssh-ca
    hostname: ca.mydomain.local
    build:
      context: .
      dockerfile: Dockerfile.ca
    # networks:
    #   my-network:
    #     aliases:
    #       - ca.mydomain.local

networks:
  my-network:
