version: '3'
services:
  server:
    container_name: ssh-server
    hostname: server.mydomain.local
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      my-network:
        aliases:
          - server.mydomain.local
  client:
    container_name: ssh-client
    hostname: laptop.mydomain.local
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      my-network:
        aliases:
          - laptop.mydomain.local
networks:
  my-network:
