FROM debian:stable

# Install SSH server
RUN apt-get update
RUN apt-get install -y openssh-server

# Create a user for SSH access
RUN useradd -m -d /home/sshuser -s /bin/bash sshuser

# disable password auth
RUN echo "PasswordAuthentication no" >> /etc/ssh/sshd_config

# this is needed to run sshd
RUN mkdir -p /var/run/sshd
CMD ["/usr/sbin/sshd", "-D"]