FROM debian:stable

# Install SSH server
RUN apt-get update
RUN apt-get install -y openssh-server

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Create a user for SSH access
RUN useradd -m -d /home/sshuser -s /bin/bash sshuser
RUN echo 'sshuser:password' | chpasswd
RUN mkdir -p /var/run/sshd

RUN echo "HostCertificate /etc/ssh/id_ed25519-cert.pub" >> /etc/ssh/sshd_config
RUN echo "HostKey /etc/ssh/id_ed25519" >> /etc/ssh/sshd_config

ENTRYPOINT ["/entrypoint.sh"]