FROM debian:stable

RUN apt-get update 
RUN apt-get install -y openssh-client

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

RUN useradd -m -d /home/sshuser -s /bin/bash sshuser
RUN echo 'sshuser:password' | chpasswd

USER sshuser

ENTRYPOINT ["/entrypoint.sh"]