FROM debian:stable

# Install SSH server
RUN apt-get update
RUN apt-get install -y openssh-server

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Create a user for SSH access
RUN useradd -m -d /home/sshuser -s /bin/bash sshuser
RUN echo 'sshuser:password' | chpasswd
RUN mkdir -p /var/run/sshd

CMD ["/usr/sbin/sshd", "-D"]