# Use the official Debian image as the base
FROM debian:stable

# Install SSH server
RUN apt-get update && apt-get install -y openssh-server

# # Create a user for SSH access (change these values as needed)
# RUN useradd -m -d /home/sshuser -s /bin/bash sshuser
# RUN echo 'sshuser:password' | chpasswd
# RUN mkdir -p /var/run/sshd

# # Start SSH server
# CMD ["/usr/sbin/sshd", "-D"]